const authData = {
  users: [
    {
      username: "John Smith",
      password: "password1",
      question: "What is your mother's maiden name?",
      answer: "Smith",
      isAccountLocked: true,
      isLoggedIn: false,
    },
    {
      username: "Emily Johnson",
      password: "password2",
      question: "What city were you born in?",
      answer: "New York",
      isAccountLocked: false,
      isLoggedIn: true,
    },
    {
      username: "Michael William",
      password: "password3",
      question: "What is the name of your first pet?",
      answer: "Max",
      isAccountLocked: false,
      isLoggedIn: false,
    },
    {
      username: "Sarah Brown",
      password: "password4",
      question: "What is your favorite book?",
      answer: "Harry Potter part1",
      isAccountLocked: true,
      isLoggedIn: false,
    },
    {
      username: "Christopher Davis",
      password: "password5",
      question: "What is your mother's maiden name?",
      answer: "Johnson",
      isAccountLocked: false,
      isLoggedIn: true,
    },
    {
      username: "Jennifer Wilson",
      password: "password6",
      question: "What city were you born in?",
      answer: "Los Angeles",
      isAccountLocked: false,
      isLoggedIn: false,
    },
    {
      username: "Matthew Taylor",
      password: "password7",
      question: "What is the name of your first pet? ",
      answer: "Fluffy",
      isAccountLocked: true,
      isLoggedIn: false,
    },
    {
      username: "Jessica Martinez",
      password: "password8",
      question: "What is your favorite book?",
      answer: "To Kill a Mockingbird",
      isAccountLocked: false,
      isLoggedIn: true,
    },
    {
      username: "Daniel Anderson",
      password: "password9",
      question: "What is your mother's maiden name?",
      answer: "Patel",
      isAccountLocked: false,
      isLoggedIn: true,
    },
    {
      username: "Elizabeth Thomas",
      password: "password10",
      question: "What city were you born in?",
      answer: "London",
      isAccountLocked: true,
      isLoggedIn: false,
    },
    {
      username: "developer",
      password: "Developer@1234",
      isAccountLocked: false,
      isAdmin: true,
      isLoggedIn: true,
    },
  ],
};

export default authData;
